      COMMON /POLYN/ POL(MX,JX,IY),POLYDX(MX,JX,IY),POLYDY(MX,JX,IY)
      COMMON /DXORDY/ UVDX(MX,JX),UVDYM(MX,JX),UVDYP(MX,JX)
      COMMON /GRADC/ GRADX(MX),GRADYM(MX,JX),GRADYP(MX,JX)
      COMMON /GAUSS/ SIA(IY),WT(IY),A
      COMMON /CSPEC/ COA(IY),COAM(IY),EL2(MX,JX),ELM2(MX,JX),EL4(MX,JX),
     * L2(MX,JX),LL(MX,JX),MM(MX)
